spring:
  datasource:
    url: jdbc:mysql://localhost:3306/givebacks
    username: root
    password: zerobase
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com #Gmail 서버 호스트
    port: 587 # Gmail의 Port 번호
    username: sri07120@gmail.com # 이메일 보내는 계정
    password: yziwwouuclmctwhb # 생성한 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            required: true
            enable: true

